# Generated by Django 5.2 on 2025-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0002_remove_game_logo_remove_game_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AlterField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(related_name='teams', to='games.game'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/team_logos/'),
        ),
    ]
