# Generated by Django 5.2 on 2025-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0003_delete_game_alter_team_games_alter_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='image',
        ),
        migrations.AlterField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='teams', to='games.game'),
        ),
    ]
