# Generated by Django 5.2 on 2025-04-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_birth_remove_profile_country'),
        ('teams', '0004_remove_tournament_image_alter_team_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
    ]
