# Generated by Django 5.2 on 2025-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_favorite_team'),
        ('teams', '0004_remove_tournament_image_alter_team_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_team',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.ManyToManyField(blank=True, to='teams.team'),
        ),
    ]
